spring:
  application:
    name: trip
  profiles:
    active: custom
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:trip;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    url: jdbc:h2:tcp://localhost/~/trip;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web.client.RestTemplate: DEBUG

springdoc:
  swagger-ui:
    use-root-path: true
    enabled: true
  api-docs:
    enabled: true

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxdT/W36UzXw5W50P94Dt
    w67wdgQ77jkvU+aLYIQICBs1V7fBdQLcwst6QysRV/FgI6octC07n0J7YvjDIbMJ
    /vSrmpFdZ522oAc346JeGVqXPnOMwnEDErWhb9lEKTMb9/WhQPFSvZuevVYyhHqi
    boz6Jwlx/rUvFt7LeDkyz/VJo09Y18JZZOOpxMNoi3Ecm6aolOkxAk1ysM7CSpDv
    KnWaGrTveg70ANydOhl2ZfAInUgj7QMh/e6HziiCdrAThwln0X5cUFBM7yygN175
    R43InlKs8ufs26+mSPh1fnU7RRkKP5MK6wQTwegkaVhbeypupX+yXYmK/Y0yUL9q
    KQIDAQAB
    -----END PUBLIC KEY-----

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: retrip-media

server:
  port: 18083
